package GUI;

import java.io.FileReader;
import java.util.Scanner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author EqeS
 */
public class Arayuz extends javax.swing.JFrame {
    //Ürün arama numaralarının açılıp açılmadığı burada kontrol edilir.
    public boolean dosyaGirdileri() {
        String bos = " ";
        try (Scanner scan = new Scanner(new FileReader("C:\\db\\urunAramaNo.txt"));) {
            if (scan.hasNext()) {
               
                    return true;

                }
                

            
        } catch (Exception e) {
        }
        return false;
    }
    
    

    /**
     * Creates new form Arayuz
     */
    public Arayuz() {

        initComponents();
        DosyaIslemleri dosya = new DosyaIslemleri();
        //Gerekli klasörler burada oluşturulur.
        dosya.klasorYaratma();
        //Bu kısımda eğer dosya açılıyorsa direkt olarak içine 1000 değeri girilir ve sayaç başlar.
        if (dosyaGirdileri()) {

        } else {
            dosya.writeFile2(String.valueOf(1000), "C:\\db\\urunAramaNo.txt");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblkayitolresim = new javax.swing.JLabel();
        lblkayitol = new javax.swing.JLabel();
        lblgirisyapresim = new javax.swing.JLabel();
        lblgirisyap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(71, 70, 68));
        jPanel1.setForeground(new java.awt.Color(71, 70, 68));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/logo.jpg"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("GUI/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("Arayuz.jLabel1.text")); // NOI18N

        lblkayitolresim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/kayitol.jpg"))); // NOI18N
        lblkayitolresim.setText(bundle.getString("Arayuz.lblkayitolresim.text")); // NOI18N
        lblkayitolresim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblkayitolresimMouseClicked(evt);
            }
        });

        lblkayitol.setFont(new java.awt.Font("Neo Sans TR", 1, 36)); // NOI18N
        lblkayitol.setForeground(new java.awt.Color(255, 153, 51));
        lblkayitol.setText(bundle.getString("Arayuz.lblkayitol.text")); // NOI18N
        lblkayitol.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblkayitolMouseDragged(evt);
            }
        });
        lblkayitol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblkayitolMouseClicked(evt);
            }
        });

        lblgirisyapresim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/girisyap.jpg"))); // NOI18N
        lblgirisyapresim.setText(bundle.getString("Arayuz.lblgirisyapresim.text")); // NOI18N
        lblgirisyapresim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblgirisyapresimMouseClicked(evt);
            }
        });

        lblgirisyap.setFont(new java.awt.Font("Neo Sans TR", 1, 36)); // NOI18N
        lblgirisyap.setForeground(new java.awt.Color(255, 153, 51));
        lblgirisyap.setText(bundle.getString("Arayuz.lblgirisyap.text")); // NOI18N
        lblgirisyap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblgirisyapMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(lblkayitolresim, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(lblgirisyapresim, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(lblkayitol, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblgirisyap, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblgirisyapresim, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblkayitolresim, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblkayitol)
                    .addComponent(lblgirisyap))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Kayıt resmine tıklandığında kayıt kısmına yönlendirir.
    private void lblkayitolresimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblkayitolresimMouseClicked
        Kayit kayit = new Kayit();
        kayit.setVisible(true);
        kayit.setBounds(600, 200, 610, 684);
        this.hide();
    }//GEN-LAST:event_lblkayitolresimMouseClicked

    private void lblkayitolMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblkayitolMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblkayitolMouseDragged

    //Giriş resmine tıklandığında giriş kısmına yönlendirir.
    private void lblgirisyapresimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblgirisyapresimMouseClicked
        Giris giris = new Giris();
        giris.setVisible(true);
        giris.setBounds(600, 200, 610, 684);
        this.hide();
    }//GEN-LAST:event_lblgirisyapresimMouseClicked
    //Kayıt yazısına tıklandığında kayıt kısmına yönlendirir.
    private void lblkayitolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblkayitolMouseClicked
        Kayit kayit = new Kayit();
        kayit.setVisible(true);
        kayit.setBounds(600, 200, 610, 684);
        this.hide();
    }//GEN-LAST:event_lblkayitolMouseClicked

    //Giriş yazısına tıklandığında giriş kısmına yönlendirir.
    private void lblgirisyapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblgirisyapMouseClicked
        Giris giris = new Giris();
        giris.setVisible(true);
        giris.setBounds(600, 200, 610, 684);
        this.hide();
    }//GEN-LAST:event_lblgirisyapMouseClicked
    private void lblkayitolresimActionPerformed(java.awt.event.ActionEvent evt) {
        Kayit kayit = new Kayit();
        kayit.setVisible(true);
        kayit.setBounds(600, 200, 610, 684);
        this.hide();
    }

    private void lblkayitolActionPerformed(java.awt.event.ActionEvent evt) {
        Kayit kayit = new Kayit();
        kayit.setVisible(true);
        kayit.setBounds(600, 200, 610, 684);
        this.hide();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GirisIslem girisIslem = new GirisIslem();
                //Kullanıcı giriş butonuna tıkladığında oturum açma işlemi için otorum dosyası oluşturulur.
                girisIslem.dosyaYarat("C:\\db\\oturum.txt");
                //Oturum kontrol sistemi çalışır eğer giriş bilgileri doğruysa oturum açılır ve sistem devam eder.
                if (girisIslem.oturumKontrol()) {
                    OturumDevam oturumDevam = new OturumDevam();

                    oturumDevam.setVisible(true);
                    oturumDevam.setBounds(600, 200, 758, 550);
                } else {
                    //Eğer yanlışsa arayüze geri döner.
                    Arayuz arayuz = new Arayuz();
                    arayuz.setVisible(true);
                    arayuz.setBounds(600, 200, 758, 550);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblgirisyap;
    private javax.swing.JLabel lblgirisyapresim;
    private javax.swing.JLabel lblkayitol;
    private javax.swing.JLabel lblkayitolresim;
    // End of variables declaration//GEN-END:variables
}
