/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.KayitIslem.kayit;
import static GUI.KayitIslem.lokasyon;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author EqeS
 */
public class Kayit extends javax.swing.JFrame {

    /**
     * Creates new form Kayit
     */
    public Kayit() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbllogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tbxkayitkullaniciadi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tbxkayitnamesurname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tbxkayitemail = new javax.swing.JTextField();
        btnkayitol = new javax.swing.JButton();
        lblKayitMesaj = new javax.swing.JLabel();
        tbxkayitSifre = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(71, 70, 68));

        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/logo.jpg"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("GUI/Bundle"); // NOI18N
        lbllogo.setText(bundle.getString("Kayit.lbllogo.text")); // NOI18N
        lbllogo.setAlignmentY(0.0F);

        jLabel2.setFont(new java.awt.Font("Neo Sans TR", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText(bundle.getString("Kayit.jLabel2.text")); // NOI18N

        tbxkayitkullaniciadi.setText(bundle.getString("Kayit.tbxkayitkullaniciadi.text")); // NOI18N
        tbxkayitkullaniciadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxkayitkullaniciadiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Neo Sans TR", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText(bundle.getString("Kayit.jLabel3.text")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Neo Sans TR", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText(bundle.getString("Kayit.jLabel4.text")); // NOI18N

        tbxkayitnamesurname.setText(bundle.getString("Kayit.tbxkayitnamesurname.text")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Neo Sans TR", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText(bundle.getString("Kayit.jLabel5.text")); // NOI18N

        tbxkayitemail.setText(bundle.getString("Kayit.tbxkayitemail.text")); // NOI18N
        tbxkayitemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxkayitemailActionPerformed(evt);
            }
        });

        btnkayitol.setBackground(new java.awt.Color(102, 102, 102));
        btnkayitol.setFont(new java.awt.Font("Neo Sans TR", 1, 18)); // NOI18N
        btnkayitol.setForeground(new java.awt.Color(255, 153, 0));
        btnkayitol.setText(bundle.getString("Kayit.btnkayitol.text")); // NOI18N
        btnkayitol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkayitolActionPerformed(evt);
            }
        });

        lblKayitMesaj.setFont(new java.awt.Font("Neo Sans TR", 0, 18)); // NOI18N
        lblKayitMesaj.setForeground(new java.awt.Color(255, 153, 0));
        lblKayitMesaj.setText(bundle.getString("Kayit.lblKayitMesaj.text")); // NOI18N

        tbxkayitSifre.setText(bundle.getString("Kayit.tbxkayitSifre.text")); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/geritusu.jpg"))); // NOI18N
        jLabel1.setText(bundle.getString("Kayit.jLabel1.text")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tbxkayitSifre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tbxkayitemail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                .addComponent(tbxkayitnamesurname, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tbxkayitkullaniciadi, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(btnkayitol, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblKayitMesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lbllogo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbxkayitkullaniciadi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbxkayitSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbxkayitnamesurname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbxkayitemail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnkayitol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKayitMesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbxkayitemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxkayitemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxkayitemailActionPerformed

    private void tbxkayitkullaniciadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxkayitkullaniciadiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxkayitkullaniciadiActionPerformed

    private void btnkayitolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkayitolActionPerformed
        KayitIslem kayitIslem = new KayitIslem();
        //Kayıt işlem class'ında verilen lokasyon ile dosya yaratılır.
        kayitIslem.dosyaYarat(kayitIslem.lokasyon);
        //Kayıt işlem class'ında kayitKontrol methodu çalıştırılır.
        if(kayitIslem.kayitKontrol(tbxkayitkullaniciadi.getText(), tbxkayitemail.getText())){
            //Eğer kullanıcı adı veya mail kullanımdaysa hata mesajı verir.
           JOptionPane.showMessageDialog(null, "Kullanıcı Adı veya Mail Zaten Kullanılmakta!");
        }else{
            //Eğer kullanıcı adı veya mail kullanımda değilse işlem devam eder ve kayıt işlemi tamamlanır.
           kayitIslem.writeFile(tbxkayitkullaniciadi.getText(), String.valueOf(tbxkayitSifre.getPassword()), tbxkayitnamesurname.getText(), tbxkayitemail.getText());
        JOptionPane.showMessageDialog(null, "Kayıt İşlemi Başarılı!");
        Arayuz arayuz = new Arayuz();
        arayuz.setVisible(true);
        arayuz.setBounds(600, 200, 758, 550);     
        this.hide(); 
        }
          
        
        
        
        
       
        
    }//GEN-LAST:event_btnkayitolActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Arayuz arayuz = new Arayuz();
        arayuz.setVisible(true);
        arayuz.setBounds(600, 200, 758, 550);     
        this.hide();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kayit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkayitol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JLabel lblKayitMesaj;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JPasswordField tbxkayitSifre;
    protected javax.swing.JTextField tbxkayitemail;
    protected javax.swing.JTextField tbxkayitkullaniciadi;
    protected javax.swing.JTextField tbxkayitnamesurname;
    // End of variables declaration//GEN-END:variables
}
