/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EqeS
 */
public class Urun extends javax.swing.JFrame {

    //Tabloda gösterilmesi için 
    DefaultTableModel model;
    urunEkleDegistir urun = new urunEkleDegistir();
    UrunAramaIslem urunArama = new UrunAramaIslem(new urunEkleDegistir());
    GirisIslem girisIslem = new GirisIslem();

    /**
     * Creates new form Urun
     */
    public Urun() {
        initComponents();
        //Oturum açan her kullanıcı ürün kısmına girdiğinde adına bir dosya oluşturulur. Bilgiler burada tutulur.
        urun.dosyaYarat("C:\\db\\urunler\\" + girisIslem.oturumKullaniciAdi() + ".txt");
        model = (DefaultTableModel) uruntable.getModel();
        try (Scanner scan = new Scanner(new FileReader("C:\\db\\urunler\\" + girisIslem.oturumKullaniciAdi() + ".txt"));) {
            while (scan.hasNextLine()) {

                String kullanıcıBilgileri = scan.nextLine();
                String[] girisArray = kullanıcıBilgileri.split(",");
                model.addRow(girisArray);
            }
        } catch (FileNotFoundException ex) {

            
        }

    }

    //Ürün durumu seçimi için kullanılır.
    public String urunDurumSecim() {
        if (jRadioButton2.isSelected()) {
            return "Mevcut";
        }
        return "Kayıp";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        uruntable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tbxUrunIsmi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tbxUrunSeriNo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(71, 70, 68));

        jLabel1.setFont(new java.awt.Font("Neo Sans TR", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("GUI/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("Urun.jLabel1.text")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/geritusu.jpg"))); // NOI18N
        jLabel2.setText(bundle.getString("Urun.jLabel2.text")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        uruntable.setBackground(new java.awt.Color(204, 204, 204));
        uruntable.setFont(new java.awt.Font("Neo Sans TR", 1, 12)); // NOI18N
        uruntable.setForeground(new java.awt.Color(255, 153, 51));
        uruntable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ürün İsmi", "Ürün Seri No", "Ürün Durumu", "Ürün Arama No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        uruntable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uruntableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(uruntable);
        if (uruntable.getColumnModel().getColumnCount() > 0) {
            uruntable.getColumnModel().getColumn(0).setResizable(false);
            uruntable.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("Urun.uruntable.columnModel.title0")); // NOI18N
            uruntable.getColumnModel().getColumn(1).setResizable(false);
            uruntable.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("Urun.uruntable.columnModel.title1")); // NOI18N
            uruntable.getColumnModel().getColumn(2).setResizable(false);
            uruntable.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("Urun.uruntable.columnModel.title2")); // NOI18N
            uruntable.getColumnModel().getColumn(3).setResizable(false);
            uruntable.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("Urun.uruntable.columnModel.title3")); // NOI18N
        }

        jLabel3.setFont(new java.awt.Font("Neo Sans TR", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText(bundle.getString("Urun.jLabel3.text")); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        tbxUrunIsmi.setText(bundle.getString("Urun.tbxUrunIsmi.text")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Neo Sans TR", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText(bundle.getString("Urun.jLabel4.text")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Neo Sans TR", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText(bundle.getString("Urun.jLabel5.text")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Neo Sans TR", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText(bundle.getString("Urun.jLabel6.text")); // NOI18N

        tbxUrunSeriNo.setText(bundle.getString("Urun.tbxUrunSeriNo.text")); // NOI18N

        jButton1.setFont(new java.awt.Font("Neo Sans TR", 1, 14)); // NOI18N
        jButton1.setText(bundle.getString("Urun.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Neo Sans TR", 1, 14)); // NOI18N
        jButton2.setText(bundle.getString("Urun.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Neo Sans TR", 1, 14)); // NOI18N
        jRadioButton2.setText(bundle.getString("Urun.jRadioButton2.text")); // NOI18N

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Neo Sans TR", 1, 14)); // NOI18N
        jRadioButton3.setText(bundle.getString("Urun.jRadioButton3.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tbxUrunIsmi, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                .addComponent(tbxUrunSeriNo))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jRadioButton2)
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton3)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbxUrunIsmi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbxUrunSeriNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(23, 23, 23))
        );

        jLabel7.setFont(new java.awt.Font("Neo Sans TR", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 51));
        jLabel7.setText(bundle.getString("Urun.jLabel7.text")); // NOI18N

        jLabel8.setFont(new java.awt.Font("Neo Sans TR", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 51));
        jLabel8.setText(bundle.getString("Urun.jLabel8.text")); // NOI18N

        jLabel9.setFont(new java.awt.Font("Neo Sans TR", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 51));
        jLabel9.setText(bundle.getString("Urun.jLabel9.text")); // NOI18N

        jLabel10.setFont(new java.awt.Font("Neo Sans TR", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 51));
        jLabel10.setText(bundle.getString("Urun.jLabel10.text")); // NOI18N

        jButton3.setFont(new java.awt.Font("Neo Sans TR", 1, 18)); // NOI18N
        jButton3.setText(bundle.getString("Urun.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(44, 44, 44))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10)))
                                .addGap(0, 28, Short.MAX_VALUE)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        KullaniciArayuzu kullaniciArayuzu = new KullaniciArayuzu();
        kullaniciArayuzu.setVisible(true);
        kullaniciArayuzu.setBounds(600, 200, 746, 476);
        this.hide();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Butona tıklandığında ürünAramano methodu çalışır.
        urun.urunAramano();
        
        //Veriler dosyaya kaydedilir.
        urun.writeFile(tbxUrunIsmi.getText(), tbxUrunSeriNo.getText(), urunDurumSecim(), urun.urunAramano());
        //ürünAramaMethodu çalıştırılır.
        urunArama.urunAramaMethod();
        int a = Integer.valueOf(urun.urunAramano());
        a = a-1;
        String ab = String.valueOf(a);
        //Tabloya listelenir.
        Object[] row = {tbxUrunIsmi.getText(), tbxUrunSeriNo.getText(), urunDurumSecim(), ab};
        model.addRow(row);
        //Ürünün eklendiğine dair bir mesaj ekrana gelir.
        JOptionPane.showMessageDialog(null, "Ürün Başarıyla Eklendi!");

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Bu kısımda ürün güncelleme için çalışır.
        Object[] row = {tbxUrunIsmi.getText(), tbxUrunSeriNo.getText(), urunDurumSecim()};
        int i = uruntable.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Lütfen listeden ürünü seçiniz!");
        }
        model.setValueAt(row[0], i, 0);
        model.setValueAt(row[1], i, 1);
        model.setValueAt(row[2], i, 2);
        //Dosya silinip tekrar yaratılır ve yeni bilgiler tekrar yazılır.
        urun.dosyaSil("C:\\db\\urunler\\" + girisIslem.oturumKullaniciAdi() + ".txt");
        urun.dosyaYarat("C:\\db\\urunler\\" + girisIslem.oturumKullaniciAdi() + ".txt");
        for (int a = 0; a < uruntable.getRowCount(); a++) {
            urun.writeFile2(model.getValueAt(a, 0).toString(), model.getValueAt(a, 1).toString(), model.getValueAt(a, 2).toString(), model.getValueAt(a, 3).toString());

        }
        model.setRowCount(0);
        try (Scanner scan = new Scanner(new FileReader("C:\\db\\urunler\\" + girisIslem.oturumKullaniciAdi() + ".txt"));) {
            while (scan.hasNextLine()) {

                String kullanıcıBilgileri = scan.nextLine();
                String[] girisArray = kullanıcıBilgileri.split(",");
                model.addRow(girisArray);
            }
        } catch (FileNotFoundException ex) {

            Logger.getLogger(Urun.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    //RadioButonlarının seçimlerini belirler.
    private void uruntableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uruntableMouseClicked
        int i = uruntable.getSelectedRow();
        tbxUrunIsmi.setText(model.getValueAt(i, 0).toString());
        tbxUrunSeriNo.setText(model.getValueAt(i, 1).toString());
        if (model.getValueAt(i, 2).equals("Mevcut")) {
            jRadioButton2.setSelected(true);
        } else if (model.getValueAt(i, 2).equals("Kayıp")) {
            jRadioButton3.setSelected(true);
        }


    }//GEN-LAST:event_uruntableMouseClicked
    //Listeden ürünü seçtikten sonra, listeden ve dosyadan ürünü silmeye başlar.
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int i = uruntable.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Lütfen listeden ürünü seçiniz!");
        }
        model.removeRow(i);
        JOptionPane.showMessageDialog(null, "Ürün Başarıyla Silindi!");
        urun.dosyaSil("C:\\db\\urunler\\" + girisIslem.oturumKullaniciAdi() + ".txt");
        urun.dosyaYarat("C:\\db\\urunler\\" + girisIslem.oturumKullaniciAdi() + ".txt");
        for (int a = 0; a < uruntable.getRowCount(); a++) {
            urun.writeFile2(model.getValueAt(a, 0).toString(), model.getValueAt(a, 1).toString(), model.getValueAt(a, 2).toString(), model.getValueAt(a, 3).toString());

        }
        model.setRowCount(0);
        try (Scanner scan = new Scanner(new FileReader("C:\\db\\urunler\\" + girisIslem.oturumKullaniciAdi() + ".txt"));) {
            while (scan.hasNextLine()) {

                String kullanıcıBilgileri = scan.nextLine();
                String[] girisArray = kullanıcıBilgileri.split(",");
                model.addRow(girisArray);
            }
        } catch (FileNotFoundException ex) {

            Logger.getLogger(Urun.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Urun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Urun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Urun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Urun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Urun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tbxUrunIsmi;
    private javax.swing.JTextField tbxUrunSeriNo;
    private javax.swing.JTable uruntable;
    // End of variables declaration//GEN-END:variables
}
